name: PowerHouse Stealth Deployer (Cedric Blazer)

on:
  repository_dispatch:
    types: [tickle_deploy]

jobs:
  deploy_node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Identity Audit
        run: |
          UA="${{ github.event.client_payload.user_agent }}"
          # This print is essential for the VPS to scrape
          curl -s -A "$UA" https://ifconfig.me/all.json 

      - name: Execute PowerHouse
        run: |
          chmod +x ./powerhouse_script.sh
          ./powerhouse_script.sh \
            "${{ secrets.RENDER_API_KEY }}" \
            "${{ secrets.GITLAB_URL }}" \
            "${{ github.event.client_payload.run_count }}"
